In [5]:
import numpy as np

A = np.array([[0, 1],             [2, 3],
              [4, 5]])
B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

C = np.dot(A, B)

print("２つの行列の積:")
print(C)

max_value = np.max(C)
print("２つの行列の積の最大値:", max_value)

２つの行列の積:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
２つの行列の積の最大値: 47
